// ********RoostGPT********
// Test generated by RoostGPT for test NodeRepo using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
import express from "express";

const app = express();
let server;

describe("Server", () => {
  beforeAll((done) => {
    server = app.listen(5000, done);
  });

  test("should start the server on port 5000", (done) => {
    const port = server.address().port;
    expect(port).toBe(5000);
    done();
  });

  afterAll((done) => {
    server.close(done);
  });
});
