// ********RoostGPT********
// Test generated by RoostGPT for test NodeRepo using AI Type Open AI and AI Model gpt-4



// ********RoostGPT********
const features = require('./features');

describe('Love Percent Generator', () => {
  let originalMathRandom;

  beforeAll(() => {
    originalMathRandom = Math.random;
  });

  afterEach(() => {
    Math.random = originalMathRandom;
  });

  test('should return 0% when Math.random returns 0', () => {
    Math.random = jest.fn().mockReturnValue(0);
    expect(features.generateLovePercent()).toBe('0%');
  });

  test('should return 100% when Math.random returns 1', () => {
    Math.random = jest.fn().mockReturnValue(0.999999);
    expect(features.generateLovePercent()).toBe('100%');
  });

  test('should return a valid percentage string for random values', () => {
    for (let i = 0; i < 100; i++) {
      Math.random = jest.fn().mockReturnValue(i / 100);
      expect(features.generateLovePercent()).toBe(`${i}%`);
    }
  });
});
