// ********RoostGPT********
/*
Test generated by RoostGPT for test aman6March using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=9ac90d269a
ROOST_METHOD_SIG_HASH=a718aa9886


*/

// ********RoostGPT********
import request from 'supertest';
import express from 'express';

const app = express();

app.get('/test', (req, res) => {
  res.status(200).json({ message: 'Server is working' });
});

describe('Test the root path', () => {
  test('It should response the GET method', async () => {
    const response = await request(app).get('/test');
    expect(response.statusCode).toBe(200);
    expect(response.body.message).toEqual('Server is working');
  });
});
