// ********RoostGPT********
/*
Test generated by RoostGPT for test aman6March using AI Type Open AI and AI Model gpt-4

ROOST_METHOD_HASH=332320feec
ROOST_METHOD_SIG_HASH=f745381c9f


*/

// ********RoostGPT********
import express from "express";
import request from "supertest";
import jwt from "jsonwebtoken";
import app from "../index.js";

jest.mock('jsonwebtoken');

describe("GET / - Homepage", () => {
  beforeEach(() => {
    jwt.verify.mockClear();
  });

  test("Should return user name if authenticated", async () => {
    const mockUser = { name: "John Doe" };
    jwt.verify.mockReturnValueOnce(mockUser);

    const response = await request(app).get("/").set('Authorization', 'Bearer token');

    expect(response.statusCode).toBe(200);
    expect(response.text).toContain(mockUser.name);
  });

  test("Should return 401 if not authenticated", async () => {
    jwt.verify.mockImplementationOnce(() => {
      throw new Error('Invalid token');
    });

    const response = await request(app).get("/");

    expect(response.statusCode).toBe(401);
  });
});
